Traceback (most recent call last):
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\utils\_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mistralai/Mistral-7B-v0.1/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\utils\hub.py", line 424, in cached_files
    hf_hub_download(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 961, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 1068, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 1596, in _raise_on_head_call_error
    raise head_call_error
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 1484, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 1401, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 285, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\file_download.py", line 309, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\huggingface_hub\utils\_http.py", line 426, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-68071d64-0ad71d164c762ae3192246f1;4594a45c-941a-4355-bd12-f10cb5bd7a0e)

Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-v0.1/resolve/main/config.json.
Access to model mistralai/Mistral-7B-v0.1 is restricted. You must have access to it and be authenticated to access it. Please log in.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ryan\Desktop\2025 Spring\CS 7643 - Deep Learning\Final project\Code\titan-project\train_mistral_lora.py", line 115, in <module>
    main()
  File "C:\Users\Ryan\Desktop\2025 Spring\CS 7643 - Deep Learning\Final project\Code\titan-project\train_mistral_lora.py", line 65, in main
    model = prepare_model(config)
  File "C:\Users\Ryan\Desktop\2025 Spring\CS 7643 - Deep Learning\Final project\Code\titan-project\code\model_preparation.py", line 28, in prepare_model
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\models\auto\auto_factory.py", line 531, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1114, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\configuration_utils.py", line 590, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\utils\hub.py", line 266, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
  File "C:\Users\Ryan\anaconda3\envs\titan_env\lib\site-packages\transformers\utils\hub.py", line 481, in cached_files
    raise OSError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/mistralai/Mistral-7B-v0.1.
401 Client Error. (Request ID: Root=1-68071d64-0ad71d164c762ae3192246f1;4594a45c-941a-4355-bd12-f10cb5bd7a0e)

Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-v0.1/resolve/main/config.json.
Access to model mistralai/Mistral-7B-v0.1 is restricted. You must have access to it and be authenticated to access it. Please log in.
